Fix appearance of the GRUB menu under Secure Boot
Without this change, the frame surrounding the GRUB menu is drawn using � chars,
instead of lines/frames-drawing chars, because the way we tried to load
the font we need does not work under Secure Boot:

  grub> loadfont $grub_dir/unicode.pf2
  error: prohibited by secure boot policy.

So let's instead do what modern Debian systems do: loadfont unicode.

Related: https://bugs.debian.org/1025352, https://bugs.debian.org/1024447

Closes #20899