rubocop: require a supported TargetRubyVersion
Fixes this:

$ rubocop --version
1.39.0
$ rubocop --format junit --out rubocop.xml --format markdown
Error: RuboCop found unknown Ruby version 3.3 in `TargetRubyVersion` parameter (in .rubocop.yml).
Supported versions: 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0, 3.1, 3.2